### PR TITLE
Feature/terraform update

### PR DESCRIPTION
**Pull request by DeployInBinary**

### CODE REVIEW

**Review by alephnull — APPROVED** [review]

**Review by excieve — APPROVED** [review]
Looks good! I'd suggest specifying required provider and module versions with pessimistic constraint operator (`~>`). And we'll need to start versioning our modules too.

**Comment by excieve** [comment]
I've just tagged [v1.0.0](https://github.com/TykTechnologies/tyk-terraform/releases/tag/v1.0.0) to seal the state of this repo for Terraform 0.11 if people are continuing to use it. Once this is merged I'll tag `v2.0.0` to mark Terraform 0.12 support.

**Comment by DeployInBinary** [comment]
> Looks good! I'd suggest specifying required provider and module versions with pessimistic constraint operator (`~>`). And we'll need to start versioning our modules too.

@excieve The constraint operator is now changed to more pessimistic one. Also modules got `version.tf` file included in previous commit.

**Comment by excieve** [comment]
@vesko-tyk I actually meant to add required versions for providers (like `aws`) and modules (like `terraform-aws-modules/vpc/aws`). Certain versions support 0.11, others 0.12, and it's a generally good thing to do.

**Comment by DeployInBinary** [comment]
@excieve I have added the required version for providers and modules. Please review and let me know, if anything else need addressing in the PR.

**Review by excieve — APPROVED** [review]

**Pull request merged**
